name: Github Pages

on:
  workflow_run:
    workflows: [Publish Release]
    types: completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: yarn install --frozen-lockfile
      - run: cp .env.github-pages .env && cat .env
      - run: yarn build

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build from artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          user_name: "GitHub Actions"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          publish_branch: gh-pages
          publish_dir: ./
